## This file is intended to be sourced, to set the feature_names list of strings
## which can then be used as a col.names list when importing the X_test.txt file
## which contains the output described in features_info.text and in features.txt.
##
## Substitutions mapping from names in features.txt to feature_names strings
##
##      A   maps to    B
##       ,    ->       .
##      ()    ->       _
##  (asdf)    ->       _asdf_
##       -    ->       .

feature_names <- c(

     # Dataset name                         # Listing in features.txt

    "tBodyAcc.mean_.X",                     # 1 tBodyAcc-mean()-X
    "tBodyAcc.mean_.Y",                     # 2 tBodyAcc-mean()-Y
    "tBodyAcc.mean_.Z",                     # 3 tBodyAcc-mean()-Z
    "tBodyAcc.std_.X",                      # 4 tBodyAcc-std()-X
    "tBodyAcc.std_.Y",                      # 5 tBodyAcc-std()-Y
    "tBodyAcc.std_.Z",                      # 6 tBodyAcc-std()-Z
    "tBodyAcc.mad_.X",                      # 7 tBodyAcc-mad()-X
    "tBodyAcc.mad_.Y",                      # 8 tBodyAcc-mad()-Y
    "tBodyAcc.mad_.Z",                      # 9 tBodyAcc-mad()-Z
    "tBodyAcc.max_.X",                      # 10 tBodyAcc-max()-X
    "tBodyAcc.max_.Y",                      # 11 tBodyAcc-max()-Y
    "tBodyAcc.max_.Z",                      # 12 tBodyAcc-max()-Z
    "tBodyAcc.min_.X",                      # 13 tBodyAcc-min()-X
    "tBodyAcc.min_.Y",                      # 14 tBodyAcc-min()-Y
    "tBodyAcc.min_.Z",                      # 15 tBodyAcc-min()-Z
    "tBodyAcc.sma_",                        # 16 tBodyAcc-sma()
    "tBodyAcc.energy_.X",                   # 17 tBodyAcc-energy()-X
    "tBodyAcc.energy_.Y",                   # 18 tBodyAcc-energy()-Y
    "tBodyAcc.energy_.Z",                   # 19 tBodyAcc-energy()-Z
    "tBodyAcc.iqr_.X",                      # 20 tBodyAcc-iqr()-X
    "tBodyAcc.iqr_.Y",                      # 21 tBodyAcc-iqr()-Y
    "tBodyAcc.iqr_.Z",                      # 22 tBodyAcc-iqr()-Z
    "tBodyAcc.entropy_.X",                  # 23 tBodyAcc-entropy()-X
    "tBodyAcc.entropy_.Y",                  # 24 tBodyAcc-entropy()-Y
    "tBodyAcc.entropy_.Z",                  # 25 tBodyAcc-entropy()-Z
    "tBodyAcc.arCoeff_.X.1",                # 26 tBodyAcc-arCoeff()-X,1
    "tBodyAcc.arCoeff_.X.2",                # 27 tBodyAcc-arCoeff()-X,2
    "tBodyAcc.arCoeff_.X.3",                # 28 tBodyAcc-arCoeff()-X,3
    "tBodyAcc.arCoeff_.X.4",                # 29 tBodyAcc-arCoeff()-X,4
    "tBodyAcc.arCoeff_.Y.1",                # 30 tBodyAcc-arCoeff()-Y,1
    "tBodyAcc.arCoeff_.Y.2",                # 31 tBodyAcc-arCoeff()-Y,2
    "tBodyAcc.arCoeff_.Y.3",                # 32 tBodyAcc-arCoeff()-Y,3
    "tBodyAcc.arCoeff_.Y.4",                # 33 tBodyAcc-arCoeff()-Y,4
    "tBodyAcc.arCoeff_.Z.1",                # 34 tBodyAcc-arCoeff()-Z,1
    "tBodyAcc.arCoeff_.Z.2",                # 35 tBodyAcc-arCoeff()-Z,2
    "tBodyAcc.arCoeff_.Z.3",                # 36 tBodyAcc-arCoeff()-Z,3
    "tBodyAcc.arCoeff_.Z.4",                # 37 tBodyAcc-arCoeff()-Z,4
    "tBodyAcc.correlation_.X.Y",            # 38 tBodyAcc-correlation()-X,Y
    "tBodyAcc.correlation_.X.Z",            # 39 tBodyAcc-correlation()-X,Z
    "tBodyAcc.correlation_.Y.Z",            # 40 tBodyAcc-correlation()-Y,Z
    "tGravityAcc.mean_.X",                  # 41 tGravityAcc-mean()-X
    "tGravityAcc.mean_.Y",                  # 42 tGravityAcc-mean()-Y
    "tGravityAcc.mean_.Z",                  # 43 tGravityAcc-mean()-Z
    "tGravityAcc.std_.X",                   # 44 tGravityAcc-std()-X
    "tGravityAcc.std_.Y",                   # 45 tGravityAcc-std()-Y
    "tGravityAcc.std_.Z",                   # 46 tGravityAcc-std()-Z
    "tGravityAcc.mad_.X",                   # 47 tGravityAcc-mad()-X
    "tGravityAcc.mad_.Y",                   # 48 tGravityAcc-mad()-Y
    "tGravityAcc.mad_.Z",                   # 49 tGravityAcc-mad()-Z
    "tGravityAcc.max_.X",                   # 50 tGravityAcc-max()-X
    "tGravityAcc.max_.Y",                   # 51 tGravityAcc-max()-Y
    "tGravityAcc.max_.Z",                   # 52 tGravityAcc-max()-Z
    "tGravityAcc.min_.X",                   # 53 tGravityAcc-min()-X
    "tGravityAcc.min_.Y",                   # 54 tGravityAcc-min()-Y
    "tGravityAcc.min_.Z",                   # 55 tGravityAcc-min()-Z
    "tGravityAcc.sma_",                     # 56 tGravityAcc-sma()
    "tGravityAcc.energy_.X",                # 57 tGravityAcc-energy()-X
    "tGravityAcc.energy_.Y",                # 58 tGravityAcc-energy()-Y
    "tGravityAcc.energy_.Z",                # 59 tGravityAcc-energy()-Z
    "tGravityAcc.iqr_.X",                   # 60 tGravityAcc-iqr()-X
    "tGravityAcc.iqr_.Y",                   # 61 tGravityAcc-iqr()-Y
    "tGravityAcc.iqr_.Z",                   # 62 tGravityAcc-iqr()-Z
    "tGravityAcc.entropy_.X",               # 63 tGravityAcc-entropy()-X
    "tGravityAcc.entropy_.Y",               # 64 tGravityAcc-entropy()-Y
    "tGravityAcc.entropy_.Z",               # 65 tGravityAcc-entropy()-Z
    "tGravityAcc.arCoeff_.X.1",             # 66 tGravityAcc-arCoeff()-X,1
    "tGravityAcc.arCoeff_.X.2",             # 67 tGravityAcc-arCoeff()-X,2
    "tGravityAcc.arCoeff_.X.3",             # 68 tGravityAcc-arCoeff()-X,3
    "tGravityAcc.arCoeff_.X.4",             # 69 tGravityAcc-arCoeff()-X,4
    "tGravityAcc.arCoeff_.Y.1",             # 70 tGravityAcc-arCoeff()-Y,1
    "tGravityAcc.arCoeff_.Y.2",             # 71 tGravityAcc-arCoeff()-Y,2
    "tGravityAcc.arCoeff_.Y.3",             # 72 tGravityAcc-arCoeff()-Y,3
    "tGravityAcc.arCoeff_.Y.4",             # 73 tGravityAcc-arCoeff()-Y,4
    "tGravityAcc.arCoeff_.Z.1",             # 74 tGravityAcc-arCoeff()-Z,1
    "tGravityAcc.arCoeff_.Z.2",             # 75 tGravityAcc-arCoeff()-Z,2
    "tGravityAcc.arCoeff_.Z.3",             # 76 tGravityAcc-arCoeff()-Z,3
    "tGravityAcc.arCoeff_.Z.4",             # 77 tGravityAcc-arCoeff()-Z,4
    "tGravityAcc.correlation_.X.Y",         # 78 tGravityAcc-correlation()-X,Y
    "tGravityAcc.correlation_.X.Z",         # 79 tGravityAcc-correlation()-X,Z
    "tGravityAcc.correlation_.Y.Z",         # 80 tGravityAcc-correlation()-Y,Z
    "tBodyAccJerk.mean_.X",                 # 81 tBodyAccJerk-mean()-X
    "tBodyAccJerk.mean_.Y",                 # 82 tBodyAccJerk-mean()-Y
    "tBodyAccJerk.mean_.Z",                 # 83 tBodyAccJerk-mean()-Z
    "tBodyAccJerk.std_.X",                  # 84 tBodyAccJerk-std()-X
    "tBodyAccJerk.std_.Y",                  # 85 tBodyAccJerk-std()-Y
    "tBodyAccJerk.std_.Z",                  # 86 tBodyAccJerk-std()-Z
    "tBodyAccJerk.mad_.X",                  # 87 tBodyAccJerk-mad()-X
    "tBodyAccJerk.mad_.Y",                  # 88 tBodyAccJerk-mad()-Y
    "tBodyAccJerk.mad_.Z",                  # 89 tBodyAccJerk-mad()-Z
    "tBodyAccJerk.max_.X",                  # 90 tBodyAccJerk-max()-X
    "tBodyAccJerk.max_.Y",                  # 91 tBodyAccJerk-max()-Y
    "tBodyAccJerk.max_.Z",                  # 92 tBodyAccJerk-max()-Z
    "tBodyAccJerk.min_.X",                  # 93 tBodyAccJerk-min()-X
    "tBodyAccJerk.min_.Y",                  # 94 tBodyAccJerk-min()-Y
    "tBodyAccJerk.min_.Z",                  # 95 tBodyAccJerk-min()-Z
    "tBodyAccJerk.sma_",                    # 96 tBodyAccJerk-sma()
    "tBodyAccJerk.energy_.X",               # 97 tBodyAccJerk-energy()-X
    "tBodyAccJerk.energy_.Y",               # 98 tBodyAccJerk-energy()-Y
    "tBodyAccJerk.energy_.Z",               # 99 tBodyAccJerk-energy()-Z
    "tBodyAccJerk.iqr_.X",                  # 100 tBodyAccJerk-iqr()-X
    "tBodyAccJerk.iqr_.Y",                  # 101 tBodyAccJerk-iqr()-Y
    "tBodyAccJerk.iqr_.Z",                  # 102 tBodyAccJerk-iqr()-Z
    "tBodyAccJerk.entropy_.X",              # 103 tBodyAccJerk-entropy()-X
    "tBodyAccJerk.entropy_.Y",              # 104 tBodyAccJerk-entropy()-Y
    "tBodyAccJerk.entropy_.Z",              # 105 tBodyAccJerk-entropy()-Z
    "tBodyAccJerk.arCoeff_.X.1",            # 106 tBodyAccJerk-arCoeff()-X,1
    "tBodyAccJerk.arCoeff_.X.2",            # 107 tBodyAccJerk-arCoeff()-X,2
    "tBodyAccJerk.arCoeff_.X.3",            # 108 tBodyAccJerk-arCoeff()-X,3
    "tBodyAccJerk.arCoeff_.X.4",            # 109 tBodyAccJerk-arCoeff()-X,4
    "tBodyAccJerk.arCoeff_.Y.1",            # 110 tBodyAccJerk-arCoeff()-Y,1
    "tBodyAccJerk.arCoeff_.Y.2",            # 111 tBodyAccJerk-arCoeff()-Y,2
    "tBodyAccJerk.arCoeff_.Y.3",            # 112 tBodyAccJerk-arCoeff()-Y,3
    "tBodyAccJerk.arCoeff_.Y.4",            # 113 tBodyAccJerk-arCoeff()-Y,4
    "tBodyAccJerk.arCoeff_.Z.1",            # 114 tBodyAccJerk-arCoeff()-Z,1
    "tBodyAccJerk.arCoeff_.Z.2",            # 115 tBodyAccJerk-arCoeff()-Z,2
    "tBodyAccJerk.arCoeff_.Z.3",            # 116 tBodyAccJerk-arCoeff()-Z,3
    "tBodyAccJerk.arCoeff_.Z.4",            # 117 tBodyAccJerk-arCoeff()-Z,4
    "tBodyAccJerk.correlation_.X.Y",        # 118 tBodyAccJerk-correlation()-X,Y
    "tBodyAccJerk.correlation_.X.Z",        # 119 tBodyAccJerk-correlation()-X,Z
    "tBodyAccJerk.correlation_.Y.Z",        # 120 tBodyAccJerk-correlation()-Y,Z
    "tBodyGyro.mean_.X",                    # 121 tBodyGyro-mean()-X
    "tBodyGyro.mean_.Y",                    # 122 tBodyGyro-mean()-Y
    "tBodyGyro.mean_.Z",                    # 123 tBodyGyro-mean()-Z
    "tBodyGyro.std_.X",                     # 124 tBodyGyro-std()-X
    "tBodyGyro.std_.Y",                     # 125 tBodyGyro-std()-Y
    "tBodyGyro.std_.Z",                     # 126 tBodyGyro-std()-Z
    "tBodyGyro.mad_.X",                     # 127 tBodyGyro-mad()-X
    "tBodyGyro.mad_.Y",                     # 128 tBodyGyro-mad()-Y
    "tBodyGyro.mad_.Z",                     # 129 tBodyGyro-mad()-Z
    "tBodyGyro.max_.X",                     # 130 tBodyGyro-max()-X
    "tBodyGyro.max_.Y",                     # 131 tBodyGyro-max()-Y
    "tBodyGyro.max_.Z",                     # 132 tBodyGyro-max()-Z
    "tBodyGyro.min_.X",                     # 133 tBodyGyro-min()-X
    "tBodyGyro.min_.Y",                     # 134 tBodyGyro-min()-Y
    "tBodyGyro.min_.Z",                     # 135 tBodyGyro-min()-Z
    "tBodyGyro.sma_",                       # 136 tBodyGyro-sma()
    "tBodyGyro.energy_.X",                  # 137 tBodyGyro-energy()-X
    "tBodyGyro.energy_.Y",                  # 138 tBodyGyro-energy()-Y
    "tBodyGyro.energy_.Z",                  # 139 tBodyGyro-energy()-Z
    "tBodyGyro.iqr_.X",                     # 140 tBodyGyro-iqr()-X
    "tBodyGyro.iqr_.Y",                     # 141 tBodyGyro-iqr()-Y
    "tBodyGyro.iqr_.Z",                     # 142 tBodyGyro-iqr()-Z
    "tBodyGyro.entropy_.X",                 # 143 tBodyGyro-entropy()-X
    "tBodyGyro.entropy_.Y",                 # 144 tBodyGyro-entropy()-Y
    "tBodyGyro.entropy_.Z",                 # 145 tBodyGyro-entropy()-Z
    "tBodyGyro.arCoeff_.X.1",               # 146 tBodyGyro-arCoeff()-X,1
    "tBodyGyro.arCoeff_.X.2",               # 147 tBodyGyro-arCoeff()-X,2
    "tBodyGyro.arCoeff_.X.3",               # 148 tBodyGyro-arCoeff()-X,3
    "tBodyGyro.arCoeff_.X.4",               # 149 tBodyGyro-arCoeff()-X,4
    "tBodyGyro.arCoeff_.Y.1",               # 150 tBodyGyro-arCoeff()-Y,1
    "tBodyGyro.arCoeff_.Y.2",               # 151 tBodyGyro-arCoeff()-Y,2
    "tBodyGyro.arCoeff_.Y.3",               # 152 tBodyGyro-arCoeff()-Y,3
    "tBodyGyro.arCoeff_.Y.4",               # 153 tBodyGyro-arCoeff()-Y,4
    "tBodyGyro.arCoeff_.Z.1",               # 154 tBodyGyro-arCoeff()-Z,1
    "tBodyGyro.arCoeff_.Z.2",               # 155 tBodyGyro-arCoeff()-Z,2
    "tBodyGyro.arCoeff_.Z.3",               # 156 tBodyGyro-arCoeff()-Z,3
    "tBodyGyro.arCoeff_.Z.4",               # 157 tBodyGyro-arCoeff()-Z,4
    "tBodyGyro.correlation_.X.Y",           # 158 tBodyGyro-correlation()-X,Y
    "tBodyGyro.correlation_.X.Z",           # 159 tBodyGyro-correlation()-X,Z
    "tBodyGyro.correlation_.Y.Z",           # 160 tBodyGyro-correlation()-Y,Z
    "tBodyGyroJerk.mean_.X",                # 161 tBodyGyroJerk-mean()-X
    "tBodyGyroJerk.mean_.Y",                # 162 tBodyGyroJerk-mean()-Y
    "tBodyGyroJerk.mean_.Z",                # 163 tBodyGyroJerk-mean()-Z
    "tBodyGyroJerk.std_.X",                 # 164 tBodyGyroJerk-std()-X
    "tBodyGyroJerk.std_.Y",                 # 165 tBodyGyroJerk-std()-Y
    "tBodyGyroJerk.std_.Z",                 # 166 tBodyGyroJerk-std()-Z
    "tBodyGyroJerk.mad_.X",                 # 167 tBodyGyroJerk-mad()-X
    "tBodyGyroJerk.mad_.Y",                 # 168 tBodyGyroJerk-mad()-Y
    "tBodyGyroJerk.mad_.Z",                 # 169 tBodyGyroJerk-mad()-Z
    "tBodyGyroJerk.max_.X",                 # 170 tBodyGyroJerk-max()-X
    "tBodyGyroJerk.max_.Y",                 # 171 tBodyGyroJerk-max()-Y
    "tBodyGyroJerk.max_.Z",                 # 172 tBodyGyroJerk-max()-Z
    "tBodyGyroJerk.min_.X",                 # 173 tBodyGyroJerk-min()-X
    "tBodyGyroJerk.min_.Y",                 # 174 tBodyGyroJerk-min()-Y
    "tBodyGyroJerk.min_.Z",                 # 175 tBodyGyroJerk-min()-Z
    "tBodyGyroJerk.sma_",                   # 176 tBodyGyroJerk-sma()
    "tBodyGyroJerk.energy_.X",              # 177 tBodyGyroJerk-energy()-X
    "tBodyGyroJerk.energy_.Y",              # 178 tBodyGyroJerk-energy()-Y
    "tBodyGyroJerk.energy_.Z",              # 179 tBodyGyroJerk-energy()-Z
    "tBodyGyroJerk.iqr_.X",                 # 180 tBodyGyroJerk-iqr()-X
    "tBodyGyroJerk.iqr_.Y",                 # 181 tBodyGyroJerk-iqr()-Y
    "tBodyGyroJerk.iqr_.Z",                 # 182 tBodyGyroJerk-iqr()-Z
    "tBodyGyroJerk.entropy_.X",             # 183 tBodyGyroJerk-entropy()-X
    "tBodyGyroJerk.entropy_.Y",             # 184 tBodyGyroJerk-entropy()-Y
    "tBodyGyroJerk.entropy_.Z",             # 185 tBodyGyroJerk-entropy()-Z
    "tBodyGyroJerk.arCoeff_.X.1",           # 186 tBodyGyroJerk-arCoeff()-X,1
    "tBodyGyroJerk.arCoeff_.X.2",           # 187 tBodyGyroJerk-arCoeff()-X,2
    "tBodyGyroJerk.arCoeff_.X.3",           # 188 tBodyGyroJerk-arCoeff()-X,3
    "tBodyGyroJerk.arCoeff_.X.4",           # 189 tBodyGyroJerk-arCoeff()-X,4
    "tBodyGyroJerk.arCoeff_.Y.1",           # 190 tBodyGyroJerk-arCoeff()-Y,1
    "tBodyGyroJerk.arCoeff_.Y.2",           # 191 tBodyGyroJerk-arCoeff()-Y,2
    "tBodyGyroJerk.arCoeff_.Y.3",           # 192 tBodyGyroJerk-arCoeff()-Y,3
    "tBodyGyroJerk.arCoeff_.Y.4",           # 193 tBodyGyroJerk-arCoeff()-Y,4
    "tBodyGyroJerk.arCoeff_.Z.1",           # 194 tBodyGyroJerk-arCoeff()-Z,1
    "tBodyGyroJerk.arCoeff_.Z.2",           # 195 tBodyGyroJerk-arCoeff()-Z,2
    "tBodyGyroJerk.arCoeff_.Z.3",           # 196 tBodyGyroJerk-arCoeff()-Z,3
    "tBodyGyroJerk.arCoeff_.Z.4",           # 197 tBodyGyroJerk-arCoeff()-Z,4
    "tBodyGyroJerk.correlation_.X.Y",       # 198 tBodyGyroJerk-correlation()-X,Y
    "tBodyGyroJerk.correlation_.X.Z",       # 199 tBodyGyroJerk-correlation()-X,Z
    "tBodyGyroJerk.correlation_.Y.Z",       # 200 tBodyGyroJerk-correlation()-Y,Z
    "tBodyAccMag.mean_",                    # 201 tBodyAccMag-mean()
    "tBodyAccMag.std_",                     # 202 tBodyAccMag-std()
    "tBodyAccMag.mad_",                     # 203 tBodyAccMag-mad()
    "tBodyAccMag.max_",                     # 204 tBodyAccMag-max()
    "tBodyAccMag.min_",                     # 205 tBodyAccMag-min()
    "tBodyAccMag.sma_",                     # 206 tBodyAccMag-sma()
    "tBodyAccMag.energy_",                  # 207 tBodyAccMag-energy()
    "tBodyAccMag.iqr_",                     # 208 tBodyAccMag-iqr()
    "tBodyAccMag.entropy_",                 # 209 tBodyAccMag-entropy()
    "tBodyAccMag.arCoeff_1",                # 210 tBodyAccMag-arCoeff()1
    "tBodyAccMag.arCoeff_2",                # 211 tBodyAccMag-arCoeff()2
    "tBodyAccMag.arCoeff_3",                # 212 tBodyAccMag-arCoeff()3
    "tBodyAccMag.arCoeff_4",                # 213 tBodyAccMag-arCoeff()4
    "tGravityAccMag.mean_",                 # 214 tGravityAccMag-mean()
    "tGravityAccMag.std_",                  # 215 tGravityAccMag-std()
    "tGravityAccMag.mad_",                  # 216 tGravityAccMag-mad()
    "tGravityAccMag.max_",                  # 217 tGravityAccMag-max()
    "tGravityAccMag.min_",                  # 218 tGravityAccMag-min()
    "tGravityAccMag.sma_",                  # 219 tGravityAccMag-sma()
    "tGravityAccMag.energy_",               # 220 tGravityAccMag-energy()
    "tGravityAccMag.iqr_",                  # 221 tGravityAccMag-iqr()
    "tGravityAccMag.entropy_",              # 222 tGravityAccMag-entropy()
    "tGravityAccMag.arCoeff_1",             # 223 tGravityAccMag-arCoeff()1
    "tGravityAccMag.arCoeff_2",             # 224 tGravityAccMag-arCoeff()2
    "tGravityAccMag.arCoeff_3",             # 225 tGravityAccMag-arCoeff()3
    "tGravityAccMag.arCoeff_4",             # 226 tGravityAccMag-arCoeff()4
    "tBodyAccJerkMag.mean_",                # 227 tBodyAccJerkMag-mean()
    "tBodyAccJerkMag.std_",                 # 228 tBodyAccJerkMag-std()
    "tBodyAccJerkMag.mad_",                 # 229 tBodyAccJerkMag-mad()
    "tBodyAccJerkMag.max_",                 # 230 tBodyAccJerkMag-max()
    "tBodyAccJerkMag.min_",                 # 231 tBodyAccJerkMag-min()
    "tBodyAccJerkMag.sma_",                 # 232 tBodyAccJerkMag-sma()
    "tBodyAccJerkMag.energy_",              # 233 tBodyAccJerkMag-energy()
    "tBodyAccJerkMag.iqr_",                 # 234 tBodyAccJerkMag-iqr()
    "tBodyAccJerkMag.entropy_",             # 235 tBodyAccJerkMag-entropy()
    "tBodyAccJerkMag.arCoeff_1",            # 236 tBodyAccJerkMag-arCoeff()1
    "tBodyAccJerkMag.arCoeff_2",            # 237 tBodyAccJerkMag-arCoeff()2
    "tBodyAccJerkMag.arCoeff_3",            # 238 tBodyAccJerkMag-arCoeff()3
    "tBodyAccJerkMag.arCoeff_4",            # 239 tBodyAccJerkMag-arCoeff()4
    "tBodyGyroMag.mean_",                   # 240 tBodyGyroMag-mean()
    "tBodyGyroMag.std_",                    # 241 tBodyGyroMag-std()
    "tBodyGyroMag.mad_",                    # 242 tBodyGyroMag-mad()
    "tBodyGyroMag.max_",                    # 243 tBodyGyroMag-max()
    "tBodyGyroMag.min_",                    # 244 tBodyGyroMag-min()
    "tBodyGyroMag.sma_",                    # 245 tBodyGyroMag-sma()
    "tBodyGyroMag.energy_",                 # 246 tBodyGyroMag-energy()
    "tBodyGyroMag.iqr_",                    # 247 tBodyGyroMag-iqr()
    "tBodyGyroMag.entropy_",                # 248 tBodyGyroMag-entropy()
    "tBodyGyroMag.arCoeff_1",               # 249 tBodyGyroMag-arCoeff()1
    "tBodyGyroMag.arCoeff_2",               # 250 tBodyGyroMag-arCoeff()2
    "tBodyGyroMag.arCoeff_3",               # 251 tBodyGyroMag-arCoeff()3
    "tBodyGyroMag.arCoeff_4",               # 252 tBodyGyroMag-arCoeff()4
    "tBodyGyroJerkMag.mean_",               # 253 tBodyGyroJerkMag-mean()
    "tBodyGyroJerkMag.std_",                # 254 tBodyGyroJerkMag-std()
    "tBodyGyroJerkMag.mad_",                # 255 tBodyGyroJerkMag-mad()
    "tBodyGyroJerkMag.max_",                # 256 tBodyGyroJerkMag-max()
    "tBodyGyroJerkMag.min_",                # 257 tBodyGyroJerkMag-min()
    "tBodyGyroJerkMag.sma_",                # 258 tBodyGyroJerkMag-sma()
    "tBodyGyroJerkMag.energy_",             # 259 tBodyGyroJerkMag-energy()
    "tBodyGyroJerkMag.iqr_",                # 260 tBodyGyroJerkMag-iqr()
    "tBodyGyroJerkMag.entropy_",            # 261 tBodyGyroJerkMag-entropy()
    "tBodyGyroJerkMag.arCoeff_1",           # 262 tBodyGyroJerkMag-arCoeff()1
    "tBodyGyroJerkMag.arCoeff_2",           # 263 tBodyGyroJerkMag-arCoeff()2
    "tBodyGyroJerkMag.arCoeff_3",           # 264 tBodyGyroJerkMag-arCoeff()3
    "tBodyGyroJerkMag.arCoeff_4",           # 265 tBodyGyroJerkMag-arCoeff()4
    "fBodyAcc.mean_.X",                     # 266 fBodyAcc-mean()-X
    "fBodyAcc.mean_.Y",                     # 267 fBodyAcc-mean()-Y
    "fBodyAcc.mean_.Z",                     # 268 fBodyAcc-mean()-Z
    "fBodyAcc.std_.X",                      # 269 fBodyAcc-std()-X
    "fBodyAcc.std_.Y",                      # 270 fBodyAcc-std()-Y
    "fBodyAcc.std_.Z",                      # 271 fBodyAcc-std()-Z
    "fBodyAcc.mad_.X",                      # 272 fBodyAcc-mad()-X
    "fBodyAcc.mad_.Y",                      # 273 fBodyAcc-mad()-Y
    "fBodyAcc.mad_.Z",                      # 274 fBodyAcc-mad()-Z
    "fBodyAcc.max_.X",                      # 275 fBodyAcc-max()-X
    "fBodyAcc.max_.Y",                      # 276 fBodyAcc-max()-Y
    "fBodyAcc.max_.Z",                      # 277 fBodyAcc-max()-Z
    "fBodyAcc.min_.X",                      # 278 fBodyAcc-min()-X
    "fBodyAcc.min_.Y",                      # 279 fBodyAcc-min()-Y
    "fBodyAcc.min_.Z",                      # 280 fBodyAcc-min()-Z
    "fBodyAcc.sma_",                        # 281 fBodyAcc-sma()
    "fBodyAcc.energy_.X",                   # 282 fBodyAcc-energy()-X
    "fBodyAcc.energy_.Y",                   # 283 fBodyAcc-energy()-Y
    "fBodyAcc.energy_.Z",                   # 284 fBodyAcc-energy()-Z
    "fBodyAcc.iqr_.X",                      # 285 fBodyAcc-iqr()-X
    "fBodyAcc.iqr_.Y",                      # 286 fBodyAcc-iqr()-Y
    "fBodyAcc.iqr_.Z",                      # 287 fBodyAcc-iqr()-Z
    "fBodyAcc.entropy_.X",                  # 288 fBodyAcc-entropy()-X
    "fBodyAcc.entropy_.Y",                  # 289 fBodyAcc-entropy()-Y
    "fBodyAcc.entropy_.Z",                  # 290 fBodyAcc-entropy()-Z
    "fBodyAcc.maxInds.X",                   # 291 fBodyAcc-maxInds-X
    "fBodyAcc.maxInds.Y",                   # 292 fBodyAcc-maxInds-Y
    "fBodyAcc.maxInds.Z",                   # 293 fBodyAcc-maxInds-Z
    "fBodyAcc.meanFreq_.X",                 # 294 fBodyAcc-meanFreq()-X
    "fBodyAcc.meanFreq_.Y",                 # 295 fBodyAcc-meanFreq()-Y
    "fBodyAcc.meanFreq_.Z",                 # 296 fBodyAcc-meanFreq()-Z
    "fBodyAcc.skewness_.X",                 # 297 fBodyAcc-skewness()-X
    "fBodyAcc.kurtosis_.X",                 # 298 fBodyAcc-kurtosis()-X
    "fBodyAcc.skewness_.Y",                 # 299 fBodyAcc-skewness()-Y
    "fBodyAcc.kurtosis_.Y",                 # 300 fBodyAcc-kurtosis()-Y
    "fBodyAcc.skewness_.Z",                 # 301 fBodyAcc-skewness()-Z
    "fBodyAcc.kurtosis_.Z",                 # 302 fBodyAcc-kurtosis()-Z
    "fBodyAcc.bandsEnergy_.1.8",            # 303 fBodyAcc-bandsEnergy()-1,8
    "fBodyAcc.bandsEnergy_.9.16",           # 304 fBodyAcc-bandsEnergy()-9,16
    "fBodyAcc.bandsEnergy_.17.24",          # 305 fBodyAcc-bandsEnergy()-17,24
    "fBodyAcc.bandsEnergy_.25.32",          # 306 fBodyAcc-bandsEnergy()-25,32
    "fBodyAcc.bandsEnergy_.33.40",          # 307 fBodyAcc-bandsEnergy()-33,40
    "fBodyAcc.bandsEnergy_.41.48",          # 308 fBodyAcc-bandsEnergy()-41,48
    "fBodyAcc.bandsEnergy_.49.56",          # 309 fBodyAcc-bandsEnergy()-49,56
    "fBodyAcc.bandsEnergy_.57.64",          # 310 fBodyAcc-bandsEnergy()-57,64
    "fBodyAcc.bandsEnergy_.1.16",           # 311 fBodyAcc-bandsEnergy()-1,16
    "fBodyAcc.bandsEnergy_.17.32",          # 312 fBodyAcc-bandsEnergy()-17,32
    "fBodyAcc.bandsEnergy_.33.48",          # 313 fBodyAcc-bandsEnergy()-33,48
    "fBodyAcc.bandsEnergy_.49.64",          # 314 fBodyAcc-bandsEnergy()-49,64
    "fBodyAcc.bandsEnergy_.1.24",           # 315 fBodyAcc-bandsEnergy()-1,24
    "fBodyAcc.bandsEnergy_.25.48",          # 316 fBodyAcc-bandsEnergy()-25,48
    "fBodyAcc.bandsEnergy_.1.8",            # 317 fBodyAcc-bandsEnergy()-1,8
    "fBodyAcc.bandsEnergy_.9.16",           # 318 fBodyAcc-bandsEnergy()-9,16
    "fBodyAcc.bandsEnergy_.17.24",          # 319 fBodyAcc-bandsEnergy()-17,24
    "fBodyAcc.bandsEnergy_.25.32",          # 320 fBodyAcc-bandsEnergy()-25,32
    "fBodyAcc.bandsEnergy_.33.40",          # 321 fBodyAcc-bandsEnergy()-33,40
    "fBodyAcc.bandsEnergy_.41.48",          # 322 fBodyAcc-bandsEnergy()-41,48
    "fBodyAcc.bandsEnergy_.49.56",          # 323 fBodyAcc-bandsEnergy()-49,56
    "fBodyAcc.bandsEnergy_.57.64",          # 324 fBodyAcc-bandsEnergy()-57,64
    "fBodyAcc.bandsEnergy_.1.16",           # 325 fBodyAcc-bandsEnergy()-1,16
    "fBodyAcc.bandsEnergy_.17.32",          # 326 fBodyAcc-bandsEnergy()-17,32
    "fBodyAcc.bandsEnergy_.33.48",          # 327 fBodyAcc-bandsEnergy()-33,48
    "fBodyAcc.bandsEnergy_.49.64",          # 328 fBodyAcc-bandsEnergy()-49,64
    "fBodyAcc.bandsEnergy_.1.24",           # 329 fBodyAcc-bandsEnergy()-1,24
    "fBodyAcc.bandsEnergy_.25.48",          # 330 fBodyAcc-bandsEnergy()-25,48
    "fBodyAcc.bandsEnergy_.1.8",            # 331 fBodyAcc-bandsEnergy()-1,8
    "fBodyAcc.bandsEnergy_.9.16",           # 332 fBodyAcc-bandsEnergy()-9,16
    "fBodyAcc.bandsEnergy_.17.24",          # 333 fBodyAcc-bandsEnergy()-17,24
    "fBodyAcc.bandsEnergy_.25.32",          # 334 fBodyAcc-bandsEnergy()-25,32
    "fBodyAcc.bandsEnergy_.33.40",          # 335 fBodyAcc-bandsEnergy()-33,40
    "fBodyAcc.bandsEnergy_.41.48",          # 336 fBodyAcc-bandsEnergy()-41,48
    "fBodyAcc.bandsEnergy_.49.56",          # 337 fBodyAcc-bandsEnergy()-49,56
    "fBodyAcc.bandsEnergy_.57.64",          # 338 fBodyAcc-bandsEnergy()-57,64
    "fBodyAcc.bandsEnergy_.1.16",           # 339 fBodyAcc-bandsEnergy()-1,16
    "fBodyAcc.bandsEnergy_.17.32",          # 340 fBodyAcc-bandsEnergy()-17,32
    "fBodyAcc.bandsEnergy_.33.48",          # 341 fBodyAcc-bandsEnergy()-33,48
    "fBodyAcc.bandsEnergy_.49.64",          # 342 fBodyAcc-bandsEnergy()-49,64
    "fBodyAcc.bandsEnergy_.1.24",           # 343 fBodyAcc-bandsEnergy()-1,24
    "fBodyAcc.bandsEnergy_.25.48",          # 344 fBodyAcc-bandsEnergy()-25,48
    "fBodyAccJerk.mean_.X",                 # 345 fBodyAccJerk-mean()-X
    "fBodyAccJerk.mean_.Y",                 # 346 fBodyAccJerk-mean()-Y
    "fBodyAccJerk.mean_.Z",                 # 347 fBodyAccJerk-mean()-Z
    "fBodyAccJerk.std_.X",                  # 348 fBodyAccJerk-std()-X
    "fBodyAccJerk.std_.Y",                  # 349 fBodyAccJerk-std()-Y
    "fBodyAccJerk.std_.Z",                  # 350 fBodyAccJerk-std()-Z
    "fBodyAccJerk.mad_.X",                  # 351 fBodyAccJerk-mad()-X
    "fBodyAccJerk.mad_.Y",                  # 352 fBodyAccJerk-mad()-Y
    "fBodyAccJerk.mad_.Z",                  # 353 fBodyAccJerk-mad()-Z
    "fBodyAccJerk.max_.X",                  # 354 fBodyAccJerk-max()-X
    "fBodyAccJerk.max_.Y",                  # 355 fBodyAccJerk-max()-Y
    "fBodyAccJerk.max_.Z",                  # 356 fBodyAccJerk-max()-Z
    "fBodyAccJerk.min_.X",                  # 357 fBodyAccJerk-min()-X
    "fBodyAccJerk.min_.Y",                  # 358 fBodyAccJerk-min()-Y
    "fBodyAccJerk.min_.Z",                  # 359 fBodyAccJerk-min()-Z
    "fBodyAccJerk.sma_",                    # 360 fBodyAccJerk-sma()
    "fBodyAccJerk.energy_.X",               # 361 fBodyAccJerk-energy()-X
    "fBodyAccJerk.energy_.Y",               # 362 fBodyAccJerk-energy()-Y
    "fBodyAccJerk.energy_.Z",               # 363 fBodyAccJerk-energy()-Z
    "fBodyAccJerk.iqr_.X",                  # 364 fBodyAccJerk-iqr()-X
    "fBodyAccJerk.iqr_.Y",                  # 365 fBodyAccJerk-iqr()-Y
    "fBodyAccJerk.iqr_.Z",                  # 366 fBodyAccJerk-iqr()-Z
    "fBodyAccJerk.entropy_.X",              # 367 fBodyAccJerk-entropy()-X
    "fBodyAccJerk.entropy_.Y",              # 368 fBodyAccJerk-entropy()-Y
    "fBodyAccJerk.entropy_.Z",              # 369 fBodyAccJerk-entropy()-Z
    "fBodyAccJerk.maxInds.X",               # 370 fBodyAccJerk-maxInds-X
    "fBodyAccJerk.maxInds.Y",               # 371 fBodyAccJerk-maxInds-Y
    "fBodyAccJerk.maxInds.Z",               # 372 fBodyAccJerk-maxInds-Z
    "fBodyAccJerk.meanFreq_.X",             # 373 fBodyAccJerk-meanFreq()-X
    "fBodyAccJerk.meanFreq_.Y",             # 374 fBodyAccJerk-meanFreq()-Y
    "fBodyAccJerk.meanFreq_.Z",             # 375 fBodyAccJerk-meanFreq()-Z
    "fBodyAccJerk.skewness_.X",             # 376 fBodyAccJerk-skewness()-X
    "fBodyAccJerk.kurtosis_.X",             # 377 fBodyAccJerk-kurtosis()-X
    "fBodyAccJerk.skewness_.Y",             # 378 fBodyAccJerk-skewness()-Y
    "fBodyAccJerk.kurtosis_.Y",             # 379 fBodyAccJerk-kurtosis()-Y
    "fBodyAccJerk.skewness_.Z",             # 380 fBodyAccJerk-skewness()-Z
    "fBodyAccJerk.kurtosis_.Z",             # 381 fBodyAccJerk-kurtosis()-Z
    "fBodyAccJerk.bandsEnergy_.1.8",        # 382 fBodyAccJerk-bandsEnergy()-1,8
    "fBodyAccJerk.bandsEnergy_.9.16",       # 383 fBodyAccJerk-bandsEnergy()-9,16
    "fBodyAccJerk.bandsEnergy_.17.24",      # 384 fBodyAccJerk-bandsEnergy()-17,24
    "fBodyAccJerk.bandsEnergy_.25.32",      # 385 fBodyAccJerk-bandsEnergy()-25,32
    "fBodyAccJerk.bandsEnergy_.33.40",      # 386 fBodyAccJerk-bandsEnergy()-33,40
    "fBodyAccJerk.bandsEnergy_.41.48",      # 387 fBodyAccJerk-bandsEnergy()-41,48
    "fBodyAccJerk.bandsEnergy_.49.56",      # 388 fBodyAccJerk-bandsEnergy()-49,56
    "fBodyAccJerk.bandsEnergy_.57.64",      # 389 fBodyAccJerk-bandsEnergy()-57,64
    "fBodyAccJerk.bandsEnergy_.1.16",       # 390 fBodyAccJerk-bandsEnergy()-1,16
    "fBodyAccJerk.bandsEnergy_.17.32",      # 391 fBodyAccJerk-bandsEnergy()-17,32
    "fBodyAccJerk.bandsEnergy_.33.48",      # 392 fBodyAccJerk-bandsEnergy()-33,48
    "fBodyAccJerk.bandsEnergy_.49.64",      # 393 fBodyAccJerk-bandsEnergy()-49,64
    "fBodyAccJerk.bandsEnergy_.1.24",       # 394 fBodyAccJerk-bandsEnergy()-1,24
    "fBodyAccJerk.bandsEnergy_.25.48",      # 395 fBodyAccJerk-bandsEnergy()-25,48
    "fBodyAccJerk.bandsEnergy_.1.8",        # 396 fBodyAccJerk-bandsEnergy()-1,8
    "fBodyAccJerk.bandsEnergy_.9.16",       # 397 fBodyAccJerk-bandsEnergy()-9,16
    "fBodyAccJerk.bandsEnergy_.17.24",      # 398 fBodyAccJerk-bandsEnergy()-17,24
    "fBodyAccJerk.bandsEnergy_.25.32",      # 399 fBodyAccJerk-bandsEnergy()-25,32
    "fBodyAccJerk.bandsEnergy_.33.40",      # 400 fBodyAccJerk-bandsEnergy()-33,40
    "fBodyAccJerk.bandsEnergy_.41.48",      # 401 fBodyAccJerk-bandsEnergy()-41,48
    "fBodyAccJerk.bandsEnergy_.49.56",      # 402 fBodyAccJerk-bandsEnergy()-49,56
    "fBodyAccJerk.bandsEnergy_.57.64",      # 403 fBodyAccJerk-bandsEnergy()-57,64
    "fBodyAccJerk.bandsEnergy_.1.16",       # 404 fBodyAccJerk-bandsEnergy()-1,16
    "fBodyAccJerk.bandsEnergy_.17.32",      # 405 fBodyAccJerk-bandsEnergy()-17,32
    "fBodyAccJerk.bandsEnergy_.33.48",      # 406 fBodyAccJerk-bandsEnergy()-33,48
    "fBodyAccJerk.bandsEnergy_.49.64",      # 407 fBodyAccJerk-bandsEnergy()-49,64
    "fBodyAccJerk.bandsEnergy_.1.24",       # 408 fBodyAccJerk-bandsEnergy()-1,24
    "fBodyAccJerk.bandsEnergy_.25.48",      # 409 fBodyAccJerk-bandsEnergy()-25,48
    "fBodyAccJerk.bandsEnergy_.1.8",        # 410 fBodyAccJerk-bandsEnergy()-1,8
    "fBodyAccJerk.bandsEnergy_.9.16",       # 411 fBodyAccJerk-bandsEnergy()-9,16
    "fBodyAccJerk.bandsEnergy_.17.24",      # 412 fBodyAccJerk-bandsEnergy()-17,24
    "fBodyAccJerk.bandsEnergy_.25.32",      # 413 fBodyAccJerk-bandsEnergy()-25,32
    "fBodyAccJerk.bandsEnergy_.33.40",      # 414 fBodyAccJerk-bandsEnergy()-33,40
    "fBodyAccJerk.bandsEnergy_.41.48",      # 415 fBodyAccJerk-bandsEnergy()-41,48
    "fBodyAccJerk.bandsEnergy_.49.56",      # 416 fBodyAccJerk-bandsEnergy()-49,56
    "fBodyAccJerk.bandsEnergy_.57.64",      # 417 fBodyAccJerk-bandsEnergy()-57,64
    "fBodyAccJerk.bandsEnergy_.1.16",       # 418 fBodyAccJerk-bandsEnergy()-1,16
    "fBodyAccJerk.bandsEnergy_.17.32",      # 419 fBodyAccJerk-bandsEnergy()-17,32
    "fBodyAccJerk.bandsEnergy_.33.48",      # 420 fBodyAccJerk-bandsEnergy()-33,48
    "fBodyAccJerk.bandsEnergy_.49.64",      # 421 fBodyAccJerk-bandsEnergy()-49,64
    "fBodyAccJerk.bandsEnergy_.1.24",       # 422 fBodyAccJerk-bandsEnergy()-1,24
    "fBodyAccJerk.bandsEnergy_.25.48",      # 423 fBodyAccJerk-bandsEnergy()-25,48
    "fBodyGyro.mean_.X",                    # 424 fBodyGyro-mean()-X
    "fBodyGyro.mean_.Y",                    # 425 fBodyGyro-mean()-Y
    "fBodyGyro.mean_.Z",                    # 426 fBodyGyro-mean()-Z
    "fBodyGyro.std_.X",                     # 427 fBodyGyro-std()-X
    "fBodyGyro.std_.Y",                     # 428 fBodyGyro-std()-Y
    "fBodyGyro.std_.Z",                     # 429 fBodyGyro-std()-Z
    "fBodyGyro.mad_.X",                     # 430 fBodyGyro-mad()-X
    "fBodyGyro.mad_.Y",                     # 431 fBodyGyro-mad()-Y
    "fBodyGyro.mad_.Z",                     # 432 fBodyGyro-mad()-Z
    "fBodyGyro.max_.X",                     # 433 fBodyGyro-max()-X
    "fBodyGyro.max_.Y",                     # 434 fBodyGyro-max()-Y
    "fBodyGyro.max_.Z",                     # 435 fBodyGyro-max()-Z
    "fBodyGyro.min_.X",                     # 436 fBodyGyro-min()-X
    "fBodyGyro.min_.Y",                     # 437 fBodyGyro-min()-Y
    "fBodyGyro.min_.Z",                     # 438 fBodyGyro-min()-Z
    "fBodyGyro.sma_",                       # 439 fBodyGyro-sma()
    "fBodyGyro.energy_.X",                  # 440 fBodyGyro-energy()-X
    "fBodyGyro.energy_.Y",                  # 441 fBodyGyro-energy()-Y
    "fBodyGyro.energy_.Z",                  # 442 fBodyGyro-energy()-Z
    "fBodyGyro.iqr_.X",                     # 443 fBodyGyro-iqr()-X
    "fBodyGyro.iqr_.Y",                     # 444 fBodyGyro-iqr()-Y
    "fBodyGyro.iqr_.Z",                     # 445 fBodyGyro-iqr()-Z
    "fBodyGyro.entropy_.X",                 # 446 fBodyGyro-entropy()-X
    "fBodyGyro.entropy_.Y",                 # 447 fBodyGyro-entropy()-Y
    "fBodyGyro.entropy_.Z",                 # 448 fBodyGyro-entropy()-Z
    "fBodyGyro.maxInds.X",                  # 449 fBodyGyro-maxInds-X
    "fBodyGyro.maxInds.Y",                  # 450 fBodyGyro-maxInds-Y
    "fBodyGyro.maxInds.Z",                  # 451 fBodyGyro-maxInds-Z
    "fBodyGyro.meanFreq_.X",                # 452 fBodyGyro-meanFreq()-X
    "fBodyGyro.meanFreq_.Y",                # 453 fBodyGyro-meanFreq()-Y
    "fBodyGyro.meanFreq_.Z",                # 454 fBodyGyro-meanFreq()-Z
    "fBodyGyro.skewness_.X",                # 455 fBodyGyro-skewness()-X
    "fBodyGyro.kurtosis_.X",                # 456 fBodyGyro-kurtosis()-X
    "fBodyGyro.skewness_.Y",                # 457 fBodyGyro-skewness()-Y
    "fBodyGyro.kurtosis_.Y",                # 458 fBodyGyro-kurtosis()-Y
    "fBodyGyro.skewness_.Z",                # 459 fBodyGyro-skewness()-Z
    "fBodyGyro.kurtosis_.Z",                # 460 fBodyGyro-kurtosis()-Z
    "fBodyGyro.bandsEnergy_.1.8",           # 461 fBodyGyro-bandsEnergy()-1,8
    "fBodyGyro.bandsEnergy_.9.16",          # 462 fBodyGyro-bandsEnergy()-9,16
    "fBodyGyro.bandsEnergy_.17.24",         # 463 fBodyGyro-bandsEnergy()-17,24
    "fBodyGyro.bandsEnergy_.25.32",         # 464 fBodyGyro-bandsEnergy()-25,32
    "fBodyGyro.bandsEnergy_.33.40",         # 465 fBodyGyro-bandsEnergy()-33,40
    "fBodyGyro.bandsEnergy_.41.48",         # 466 fBodyGyro-bandsEnergy()-41,48
    "fBodyGyro.bandsEnergy_.49.56",         # 467 fBodyGyro-bandsEnergy()-49,56
    "fBodyGyro.bandsEnergy_.57.64",         # 468 fBodyGyro-bandsEnergy()-57,64
    "fBodyGyro.bandsEnergy_.1.16",          # 469 fBodyGyro-bandsEnergy()-1,16
    "fBodyGyro.bandsEnergy_.17.32",         # 470 fBodyGyro-bandsEnergy()-17,32
    "fBodyGyro.bandsEnergy_.33.48",         # 471 fBodyGyro-bandsEnergy()-33,48
    "fBodyGyro.bandsEnergy_.49.64",         # 472 fBodyGyro-bandsEnergy()-49,64
    "fBodyGyro.bandsEnergy_.1.24",          # 473 fBodyGyro-bandsEnergy()-1,24
    "fBodyGyro.bandsEnergy_.25.48",         # 474 fBodyGyro-bandsEnergy()-25,48
    "fBodyGyro.bandsEnergy_.1.8",           # 475 fBodyGyro-bandsEnergy()-1,8
    "fBodyGyro.bandsEnergy_.9.16",          # 476 fBodyGyro-bandsEnergy()-9,16
    "fBodyGyro.bandsEnergy_.17.24",         # 477 fBodyGyro-bandsEnergy()-17,24
    "fBodyGyro.bandsEnergy_.25.32",         # 478 fBodyGyro-bandsEnergy()-25,32
    "fBodyGyro.bandsEnergy_.33.40",         # 479 fBodyGyro-bandsEnergy()-33,40
    "fBodyGyro.bandsEnergy_.41.48",         # 480 fBodyGyro-bandsEnergy()-41,48
    "fBodyGyro.bandsEnergy_.49.56",         # 481 fBodyGyro-bandsEnergy()-49,56
    "fBodyGyro.bandsEnergy_.57.64",         # 482 fBodyGyro-bandsEnergy()-57,64
    "fBodyGyro.bandsEnergy_.1.16",          # 483 fBodyGyro-bandsEnergy()-1,16
    "fBodyGyro.bandsEnergy_.17.32",         # 484 fBodyGyro-bandsEnergy()-17,32
    "fBodyGyro.bandsEnergy_.33.48",         # 485 fBodyGyro-bandsEnergy()-33,48
    "fBodyGyro.bandsEnergy_.49.64",         # 486 fBodyGyro-bandsEnergy()-49,64
    "fBodyGyro.bandsEnergy_.1.24",          # 487 fBodyGyro-bandsEnergy()-1,24
    "fBodyGyro.bandsEnergy_.25.48",         # 488 fBodyGyro-bandsEnergy()-25,48
    "fBodyGyro.bandsEnergy_.1.8",           # 489 fBodyGyro-bandsEnergy()-1,8
    "fBodyGyro.bandsEnergy_.9.16",          # 490 fBodyGyro-bandsEnergy()-9,16
    "fBodyGyro.bandsEnergy_.17.24",         # 491 fBodyGyro-bandsEnergy()-17,24
    "fBodyGyro.bandsEnergy_.25.32",         # 492 fBodyGyro-bandsEnergy()-25,32
    "fBodyGyro.bandsEnergy_.33.40",         # 493 fBodyGyro-bandsEnergy()-33,40
    "fBodyGyro.bandsEnergy_.41.48",         # 494 fBodyGyro-bandsEnergy()-41,48
    "fBodyGyro.bandsEnergy_.49.56",         # 495 fBodyGyro-bandsEnergy()-49,56
    "fBodyGyro.bandsEnergy_.57.64",         # 496 fBodyGyro-bandsEnergy()-57,64
    "fBodyGyro.bandsEnergy_.1.16",          # 497 fBodyGyro-bandsEnergy()-1,16
    "fBodyGyro.bandsEnergy_.17.32",         # 498 fBodyGyro-bandsEnergy()-17,32
    "fBodyGyro.bandsEnergy_.33.48",         # 499 fBodyGyro-bandsEnergy()-33,48
    "fBodyGyro.bandsEnergy_.49.64",         # 500 fBodyGyro-bandsEnergy()-49,64
    "fBodyGyro.bandsEnergy_.1.24",          # 501 fBodyGyro-bandsEnergy()-1,24
    "fBodyGyro.bandsEnergy_.25.48",         # 502 fBodyGyro-bandsEnergy()-25,48
    "fBodyAccMag.mean_",                    # 503 fBodyAccMag-mean()
    "fBodyAccMag.std_",                     # 504 fBodyAccMag-std()
    "fBodyAccMag.mad_",                     # 505 fBodyAccMag-mad()
    "fBodyAccMag.max_",                     # 506 fBodyAccMag-max()
    "fBodyAccMag.min_",                     # 507 fBodyAccMag-min()
    "fBodyAccMag.sma_",                     # 508 fBodyAccMag-sma()
    "fBodyAccMag.energy_",                  # 509 fBodyAccMag-energy()
    "fBodyAccMag.iqr_",                     # 510 fBodyAccMag-iqr()
    "fBodyAccMag.entropy_",                 # 511 fBodyAccMag-entropy()
    "fBodyAccMag.maxInds",                  # 512 fBodyAccMag-maxInds
    "fBodyAccMag.meanFreq_",                # 513 fBodyAccMag-meanFreq()
    "fBodyAccMag.skewness_",                # 514 fBodyAccMag-skewness()
    "fBodyAccMag.kurtosis_",                # 515 fBodyAccMag-kurtosis()
    "fBodyBodyAccJerkMag.mean_",            # 516 fBodyBodyAccJerkMag-mean()
    "fBodyBodyAccJerkMag.std_",             # 517 fBodyBodyAccJerkMag-std()
    "fBodyBodyAccJerkMag.mad_",             # 518 fBodyBodyAccJerkMag-mad()
    "fBodyBodyAccJerkMag.max_",             # 519 fBodyBodyAccJerkMag-max()
    "fBodyBodyAccJerkMag.min_",             # 520 fBodyBodyAccJerkMag-min()
    "fBodyBodyAccJerkMag.sma_",             # 521 fBodyBodyAccJerkMag-sma()
    "fBodyBodyAccJerkMag.energy_",          # 522 fBodyBodyAccJerkMag-energy()
    "fBodyBodyAccJerkMag.iqr_",             # 523 fBodyBodyAccJerkMag-iqr()
    "fBodyBodyAccJerkMag.entropy_",         # 524 fBodyBodyAccJerkMag-entropy()
    "fBodyBodyAccJerkMag.maxInds",          # 525 fBodyBodyAccJerkMag-maxInds
    "fBodyBodyAccJerkMag.meanFreq_",        # 526 fBodyBodyAccJerkMag-meanFreq()
    "fBodyBodyAccJerkMag.skewness_",        # 527 fBodyBodyAccJerkMag-skewness()
    "fBodyBodyAccJerkMag.kurtosis_",        # 528 fBodyBodyAccJerkMag-kurtosis()
    "fBodyBodyGyroMag.mean_",               # 529 fBodyBodyGyroMag-mean()
    "fBodyBodyGyroMag.std_",                # 530 fBodyBodyGyroMag-std()
    "fBodyBodyGyroMag.mad_",                # 531 fBodyBodyGyroMag-mad()
    "fBodyBodyGyroMag.max_",                # 532 fBodyBodyGyroMag-max()
    "fBodyBodyGyroMag.min_",                # 533 fBodyBodyGyroMag-min()
    "fBodyBodyGyroMag.sma_",                # 534 fBodyBodyGyroMag-sma()
    "fBodyBodyGyroMag.energy_",             # 535 fBodyBodyGyroMag-energy()
    "fBodyBodyGyroMag.iqr_",                # 536 fBodyBodyGyroMag-iqr()
    "fBodyBodyGyroMag.entropy_",            # 537 fBodyBodyGyroMag-entropy()
    "fBodyBodyGyroMag.maxInds",             # 538 fBodyBodyGyroMag-maxInds
    "fBodyBodyGyroMag.meanFreq_",           # 539 fBodyBodyGyroMag-meanFreq()
    "fBodyBodyGyroMag.skewness_",           # 540 fBodyBodyGyroMag-skewness()
    "fBodyBodyGyroMag.kurtosis_",           # 541 fBodyBodyGyroMag-kurtosis()
    "fBodyBodyGyroJerkMag.mean_",           # 542 fBodyBodyGyroJerkMag-mean()
    "fBodyBodyGyroJerkMag.std_",            # 543 fBodyBodyGyroJerkMag-std()
    "fBodyBodyGyroJerkMag.mad_",            # 544 fBodyBodyGyroJerkMag-mad()
    "fBodyBodyGyroJerkMag.max_",            # 545 fBodyBodyGyroJerkMag-max()
    "fBodyBodyGyroJerkMag.min_",            # 546 fBodyBodyGyroJerkMag-min()
    "fBodyBodyGyroJerkMag.sma_",            # 547 fBodyBodyGyroJerkMag-sma()
    "fBodyBodyGyroJerkMag.energy_",         # 548 fBodyBodyGyroJerkMag-energy()
    "fBodyBodyGyroJerkMag.iqr_",            # 549 fBodyBodyGyroJerkMag-iqr()
    "fBodyBodyGyroJerkMag.entropy_",        # 550 fBodyBodyGyroJerkMag-entropy()
    "fBodyBodyGyroJerkMag.maxInds",         # 551 fBodyBodyGyroJerkMag-maxInds
    "fBodyBodyGyroJerkMag.meanFreq_",       # 552 fBodyBodyGyroJerkMag-meanFreq()
    "fBodyBodyGyroJerkMag.skewness_",       # 553 fBodyBodyGyroJerkMag-skewness()
    "fBodyBodyGyroJerkMag.kurtosis_",       # 554 fBodyBodyGyroJerkMag-kurtosis()
    "angle_tBodyAccMean.gravity_",          # 555 angle(tBodyAccMean,gravity)
    "angle_tBodyAccJerkMean_.gravityMean_", # 556 angle(tBodyAccJerkMean),gravityMean)
    "angle_tBodyGyroMean.gravityMean_",     # 557 angle(tBodyGyroMean,gravityMean)
    "angle_tBodyGyroJerkMean.gravityMean_", # 558 angle(tBodyGyroJerkMean,gravityMean)
    "angle_X.gravityMean_",                 # 559 angle(X,gravityMean)
    "angle_Y.gravityMean_",                 # 560 angle(Y,gravityMean)
    "angle_Z.gravityMean_"                  # 561 angle(Z,gravityMean)
)
